### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by d2dyno**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by j0nnymoe** [comment]
Thanks but already in process - https://github.com/linuxserver/docker-qbittorrent/issues/35

**Comment by d2dyno** [comment]
Why not bump wile pipeline is in progress?

**Comment by j0nnymoe** [comment]
Because from the issue I linked, it seems one of our devs had issues with just bumping the versions.

**Comment by d2dyno** [comment]
Sorry, I read 

> FYI, the python dependency was a fluke in v4.1.4. Python continues to be optional. In v4.1.5 python won't be queried if the user hasn't enabled the search engines functionality.

And assuming no one had tried the newest version's fix for the issue.

**Comment by j0nnymoe** [comment]
If you could test the build that's posted in that issue, it would be a great help

**Pull request closed without merging**
