### PR TITLE
Missing if statements fixed

### PR DESCRIPTION
**Pull request by faab007**
Config was copying even if it already existed.
Code has been tested.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x ] I have read the [contributing](https://github.com/linuxserver/docker-qbittorrent/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Corrected if statements in root/etc/cont-init.d/30-config

## Benefits of this PR and context:

No issue was created for this problem

## How Has This Been Tested?

Code has been run on a docker container with qBittorrent installed

### CODE REVIEW

**Comment by tobbenb** [comment]
If is not needed when using [[ ]]

**Comment by faab007** [comment]
Yes they were. When not using if it was always copying the config

**Comment by aptalca** [comment]
`If/then` and `[[ ... ]] &&` Do the same thing in this case. There is no need for this PR.

**Comment by faab007** [comment]
That's not true. It was copying the config even if it existed and after I added the if's it wasn't copying the config.

**Comment by tobbenb** [comment]
It is true. 
How do you check if the file is copied over? The time for modifying the file? qbittorrent saves to the file every time you restart the container.

**Comment by faab007** [comment]
Yea I changed something in the config file in the volume and when I restarted the container it was over written.
Then I edited the 30-config file and did the same thing again and it didn't copy it.
I also deleted the entire config file in the volume and it got copied over.

Maybe its a 1 in a 100 chance that it doesn't work or something but it wasn't for me.

**Comment by Roxedus** [comment]
> That's not true

Can you point to any documentation stating this? We use this syntax in lots of images, it does what we expect it to do.

**Pull request closed without merging**
