### PR TITLE
Fix issue #70 and docker-compose.yml example

### LINKED ISSUE #70: Could not parse Nova search engine capabilities
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

Search engine plugins are not being added/installed

## Expected Behavior

Search engine plugins should be installed

## Current Behavior
Web UI does not do anything when installing a search plugin

## Steps to Reproduce

1. docker-compose up
2. login to webui localhost:8080
3. add a search plugin

## Environment
**OS: MAC Catalina 10.15.4**      
**CPU architecture:** x86_64      
**How docker service was installed:**      
brew installation

## Command used to create docker container (run/create/compose/screenshot)
$ docker-compose up
```
---
# docker-compose.yml
version: "3"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /Users/rchenzheng/test/qbittorrent/config:/config
      - /Users/rchenzheng/test/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
```

## Docker logs
```
Could not parse Nova search engine capabilities, msg:
Error:  Traceback (most recent call last):
  File "/config/data/qBittorrent/nova3/nova2.py", line 36, in <module>
    import urllib.parse
ImportError: No module named parse

Could not parse Nova search engine capabilities, msg:
Error:  Traceback (most recent call last):
  File "/config/data/qBittorrent/nova3/nova2.py", line 36, in <module>
    import urllib.parse
ImportError: No module named parse

Could not parse Nova search engine capabilities, msg:
Error:  Traceback (most recent call last):
  File "/config/data/qBittorrent/nova3/nova2.py", line 36, in <module>
    import urllib.parse
ImportError: No module named parse

Could not parse Nova search engine capabilities, msg:
Error:  Traceback (most recent call last):
  File "/config/data/qBittorrent/nova3/nova2.py", line 36, in <module>
    import urllib.parse
ImportError: No module named parse

Could not parse Nova search engine capabilities, msg:
Error:  Traceback (most recent call last):
  File "/config/data/qBittorrent/nova3/nova2.py", line 36, in <module>
    import urllib.parse
ImportError: No module named parse

Could not parse Nova search engine capabilities, msg:
Error:  Traceback (most recent call last):
  File "/config/data/qBittorrent/nova3/nova2.py", line 36, in <module>
    import urllib.parse
ImportError: No module named parse

Could not parse Nova search engine capabilities, msg:
Error:  Traceback (most recent call last):
  File "/config/data/qBittorrent/nova3/nova2.py", line 36, in <module>
    import urllib.parse
ImportError: No module named parse
```

### PR DESCRIPTION
**Pull request by rchenzheng**
- Upgrade to python3 to fix search engine plugin support
- Add docker-compose.yml

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

------------------------------

We welcome all PR’s though this doesn’t guarantee it will be accepted.

## Description:
Migrate to python3 and add docker-compose

## Benefits of this PR and context:
Fixes #70
## How Has This Been Tested?
Yes, docker build and add plugin

### CODE REVIEW

**Comment by thelamer** [comment]
We don't do compose examples like that , it is in our readme please pull that
I am ok with python3 side by side with python2 , we have done that for other images 
In bionic when you install python3 it is a unique bin so they can exist side by side
Though we would need to revisit this when we innevitably rebase to focal

**Comment by rchenzheng** [comment]
> We don't do compose examples like that , it is in our readme please pull that
> I am ok with python3 side by side with python2 , we have done that for other images
> In bionic when you install python3 it is a unique bin so they can exist side by side
> Though we would need to revisit this when we innevitably rebase to focal

Where are the examples? There seems to be a lack of documentation around it

**Comment by SnufflesC137** [comment]
Let's get merging!

**Comment by thelamer** [comment]
Again python3 should be installed alongside python , make sure they are in alphabetical order. 
Also I cannot fathom missing the heading 2 docker compose section of the readme especially after being told by the maintainer it is in there.

**Comment by rchenzheng** [comment]
> Again python3 should be installed alongside python , make sure they are in alphabetical order.
> Also I cannot fathom missing the heading 2 docker compose section of the readme especially after being told by the maintainer it is in there.

It's been fixed, however I think it's an oversight that the biggest function of the qbittorrent is broken.

The unit tests should have caught it

**Comment by thelamer** [comment]
Please enlighten us, what unit tests would have caught this ? 
We maintain hundreds of containers across many platforms and allready apply custom CI to spin them up and grab screenshots. 
https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/qbittorrent/latest/index.html

In general I do not appreciate you overall tone , we have zero control over the upstream projects we ingest and you just act like we should be running custom selenium tests on top of divs we don't even control the names/IDs of. 

How would you implement/maintain a testing framework to span our library of images ?

**Pull request merged**
